version: "3.7"
services:
  nginx:
    build:
      context: ./docker
      dockerfile: development/nginx/Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8080:80"
  php-fpm:
    build:
      context: ./docker
      dockerfile: development/php-fpm/Dockerfile
    volumes:
      - ./:/app
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      PHP_IDE_CONFIG: serverName=API
  php-cli:
    build:
      context: ./docker
      dockerfile: development/php-cli/Dockerfile
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
    volumes:
      - ./:/app
    working_dir: /app
    tty: true