version: "3.7"
services:
    nginx:
        build:
            context: ./docker
            dockerfile: development/nginx/Dockerfile
        volumes:
            - ./:/app
        ports:
            - "8080:80"
    php-fpm:
        build:
            context: ./docker
            dockerfile: development/php-fpm/Dockerfile
        volumes:
            - ./:/app
        environment:
            APP_ENV: dev
            APP_DEBUG: 1
            PHP_IDE_CONFIG: serverName=API
            DB_HOST: api-postgres
            DB_USER: app
            DB_PASSWORD: secret
            DB_NAME: app
    php-cli:
        build:
            context: ./docker
            dockerfile: development/php-cli/Dockerfile
        environment:
            APP_ENV: dev
            APP_DEBUG: 1
            DB_HOST: api-postgres
            DB_USER: app
            DB_PASSWORD: secret
            DB_NAME: app
        volumes:
            - ./:/app
        working_dir: /app
        tty: true
    api-postgres:
        image: postgres:12.2-alpine
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: app
        volumes:
            - api-postgres:/var/lib/postgresql/data
        ports:
            - "54321:5432"
volumes:
    api-postgres: